package wolf

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Port is one port Wolf listens on.
type Port struct {
	Name  string
	Proto string
	Num   int
}

// Ports is Wolf's layout around the base port (Wolf's defaults at 47989:
// tcp 47984, 47989, 48010; udp 47999, 48100, 48200).
func Ports(base int) []Port {
	if base == 0 {
		base = 47989
	}
	return []Port{
		{"https", "tcp", base - 5}, {"http", "tcp", base}, {"rtsp", "tcp", base + 21},
		{"control", "udp", base + 10}, {"video", "udp", base + 111}, {"audio", "udp", base + 211},
	}
}

// offlimits are the destinations the session may not open connections to:
// this host's other networks and every private, CGNAT (the tailnet) and
// special-purpose range. The internet stays reachable: the launcher logs in
// and patches.
var offlimits = []string{"0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16",
	"172.16.0.0/12", "192.0.0.0/24", "192.168.0.0/16", "198.18.0.0/15", "224.0.0.0/4", "240.0.0.0/4"}

// Firewall is the nft table xivstream-wolf-firewall.service loads while Wolf
// runs. It only ever drops (or DNATs): firewalld still decides everything it
// does not drop. The session is matched by its bridge, not its address: a
// container with NET_ADMIN could change the address.
func Firewall(s Setup) []byte {
	w := s.Wolf
	bridge := BridgeName(w.Network)
	gw := w.Gateway().String()
	var tcp, udp []string
	for _, p := range Ports(s.Stream.PortBase) {
		if p.Proto == "tcp" {
			tcp = append(tcp, strconv.Itoa(p.Num))
		} else {
			udp = append(udp, strconv.Itoa(p.Num))
		}
	}
	var fwd []string
	for _, f := range w.Forwards {
		fwd = append(fwd, strconv.Itoa(f.Port))
	}
	sort.Slice(fwd, func(i, j int) bool { a, _ := strconv.Atoi(fwd[i]); b, _ := strconv.Atoi(fwd[j]); return a < b })

	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	p("# xivstream: Wolf's network policy. (Generated by xivstream; loaded by")
	p("# %s while Wolf runs.)", FirewallUnit)
	p("#")
	p("# Wolf binds every IPv4 address with no option to choose one: its ports are")
	p("# for loopback and the tailnet clients only. The game's session sits on the")
	p("# %s bridge (%s): it may reach the host only at the gateway's forwards,", bridge, w.Subnet)
	p("# and never the tailnet or a private network; the internet stays open.")
	p("# Tailnet peers that reached the old Incus game container keep reaching")
	p("# the session at the same address.")
	p("table inet %s", Table)
	p("delete table inet %s", Table)
	p("")
	p("table inet %s {", Table)
	p("\tset offlimits4 {")
	p("\t\ttype ipv4_addr")
	p("\t\tflags interval")
	p("\t\telements = { %s }", strings.Join(offlimits, ", "))
	p("\t}")
	if len(w.AllowedClients) > 0 {
		p("")
		p("\tset wolf_clients {")
		p("\t\ttype ipv4_addr")
		p("\t\tflags interval")
		p("\t\telements = { %s }", strings.Join(w.AllowedClients, ", "))
		p("\t}")
	}
	inbound := s.LegacyAddress != "" && len(w.Inbound.Ports) > 0 && len(w.Inbound.Peers) > 0
	var inPorts []string
	if inbound {
		for _, n := range w.Inbound.Ports {
			inPorts = append(inPorts, strconv.Itoa(n))
		}
		p("")
		p("\tset inbound_peers {")
		p("\t\ttype ipv4_addr")
		p("\t\tflags interval")
		p("\t\telements = { %s }", strings.Join(w.Inbound.Peers, ", "))
		p("\t}")
	}
	p("")
	p("\tchain input {")
	p("\t\ttype filter hook input priority filter - 10; policy accept;")
	p("\t\t# Wolf: loopback, and the allowed clients over Tailscale")
	p("\t\ttcp dport { %s } iifname \"lo\" accept", strings.Join(tcp, ", "))
	p("\t\tudp dport { %s } iifname \"lo\" accept", strings.Join(udp, ", "))
	clients := ""
	if len(w.AllowedClients) > 0 {
		clients = " ip saddr @wolf_clients"
	}
	p("\t\ttcp dport { %s } iifname \"tailscale0\"%s accept", strings.Join(tcp, ", "), clients)
	p("\t\tudp dport { %s } iifname \"tailscale0\"%s accept", strings.Join(udp, ", "), clients)
	p("\t\ttcp dport { %s } counter drop", strings.Join(tcp, ", "))
	p("\t\tudp dport { %s } counter drop", strings.Join(udp, ", "))
	p("\t\t# the session: replies, and the forwards on its gateway; nothing else here")
	p("\t\tiifname \"%s\" ct state established,related accept", bridge)
	if len(fwd) > 0 {
		p("\t\tiifname \"%s\" ip daddr %s tcp dport { %s } accept", bridge, gw, strings.Join(fwd, ", "))
	}
	p("\t\tiifname \"%s\" counter drop", bridge)
	if len(fwd) > 0 {
		p("\t\t# the forwards are the session's (and Wolf's PulseAudio's, for the microphone)")
		p("\t\tip daddr %s tcp dport { %s } iifname != \"lo\" counter drop", gw, strings.Join(fwd, ", "))
	}
	p("\t}")
	p("")
	p("\tchain forward {")
	p("\t\ttype filter hook forward priority filter - 10; policy accept;")
	p("\t\tiifname \"%s\" ct state established,related accept", bridge)
	p("\t\tiifname \"%s\" meta nfproto ipv6 counter drop", bridge)
	p("\t\tiifname \"%s\" oifname \"tailscale0\" counter drop", bridge)
	p("\t\tiifname \"%s\" ip daddr @offlimits4 counter drop", bridge)
	p("\t\toifname \"%s\" ct state established,related accept", bridge)
	if inbound {
		p("\t\toifname \"%s\" ip daddr %s tcp dport { %s } ip saddr @inbound_peers accept", bridge, w.AppIP, strings.Join(inPorts, ", "))
	}
	p("\t\toifname \"%s\" counter drop", bridge)
	p("\t}")
	if inbound {
		p("")
		p("\t# The old game container's address (%s, its subnet route and tailnet ACL", s.LegacyAddress)
		p("\t# stay as they were) now leads to the session.")
		p("\tchain prerouting {")
		p("\t\ttype nat hook prerouting priority dstnat - 10; policy accept;")
		p("\t\tip daddr %s tcp dport { %s } ip saddr @inbound_peers dnat ip to %s", s.LegacyAddress, strings.Join(inPorts, ", "), w.AppIP)
		p("\t}")
		p("")
		p("\tchain output {")
		p("\t\ttype nat hook output priority dstnat - 10; policy accept;")
		p("\t\tip daddr %s tcp dport { %s } dnat ip to %s", s.LegacyAddress, strings.Join(inPorts, ", "), w.AppIP)
		p("\t}")
	}
	p("}")
	return []byte(b.String())
}
