package wolf

import (
	"fmt"
	"strings"

	"github.com/Spaceghost/xivstream-dalamud/internal/config"
)

// nvidiaNodes are the NVIDIA device nodes Wolf's container is given. Quadlet
// decides an optional device ("AddDevice=-...") when it generates the unit,
// which at boot is before anything has created nvidia-uvm or -modeset; so
// with nvidia-modprobe the core nodes are required, and created by
// ExecStartPre just before podman runs. The nvidia-caps nodes are MIG-only
// and not given.
var nvidiaNodes = []string{"/dev/nvidia0", "/dev/nvidiactl", "/dev/nvidia-modeset", "/dev/nvidia-uvm"}

const nvidiaOptional = "/dev/nvidia-uvm-tools"

// Quadlet is Wolf's rootful Podman unit: Wolf's documented setup (host
// network, the Podman socket as Docker's, /dev and /run/udev for the virtual
// devices) with the NVIDIA driver volume, a pinned image, and the ordering
// that keeps it away from the Incus game and an unmounted home.
func Quadlet(s Setup) []byte {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	w("# xivstream: Wolf, rootful. (Generated by xivstream; edit the config and")
	w("# re-run `xivstream apply` instead of this file.)")
	w("[Unit]")
	w("Description=Wolf game streaming server (xivstream)")
	w("Documentation=https://games-on-whales.github.io/wolf/stable/")
	deps := []string{"podman.socket", FirewallUnit}
	if s.NVIDIA {
		deps = append(deps, DriverVolUnit)
	}
	w("Requires=%s", strings.Join(deps, " "))
	w("Wants=network-online.target")
	w("After=network-online.target tailscaled.service %s", strings.Join(deps, " "))
	w("# The game's home: never start on the bare mountpoint (an empty home would")
	w("# make XIVLauncher start a fresh install).")
	w("RequiresMountsFor=%s", s.Wolf.Home)
	if s.Fallback {
		w("# One streaming server at a time: starting either stops the other, and")
		w("# the Incus container is down before the preflight looks.")
		w("Conflicts=%s", FallbackUnit)
		w("After=%s", FallbackUnit)
	}
	w("StartLimitIntervalSec=600")
	w("StartLimitBurst=5")
	w("")
	w("[Container]")
	w("ContainerName=wolf")
	w("HostName=wolf")
	w("Image=%s", s.serverImage())
	w("Network=host")
	w("SecurityLabelDisable=true")
	w(`PodmanArgs=--ipc=host --device-cgroup-rule "c 13:* rmw"`)
	w("AddDevice=/dev/dri")
	w("AddDevice=/dev/uinput")
	w("AddDevice=/dev/uhid")
	if s.NVIDIA {
		optional := "-"
		if s.Modprobe {
			optional = ""
		}
		for _, n := range nvidiaNodes {
			w("AddDevice=%s%s", optional, n)
		}
		w("AddDevice=-%s", nvidiaOptional)
		w("Volume=%s:/usr/nvidia:rw", DriverVolume)
		w("Environment=NVIDIA_DRIVER_VOLUME_NAME=%s", DriverVolume)
	}
	w("Volume=/etc/wolf:/etc/wolf:rw")
	w("Volume=/run/podman/podman.sock:/var/run/docker.sock:rw")
	w("Volume=/dev:/dev:rw")
	w("Volume=/run/udev:/run/udev:rw")
	w("# Wolf's sockets (its API for `xivstream pair`, each session's Wayland and")
	w("# PulseAudio) on the host, where the session containers are given them.")
	w("Volume=%s:%s:rw", HostRuntimeDir, RuntimeDir)
	w("Environment=XDG_RUNTIME_DIR=%s", RuntimeDir)
	w("Environment=WOLF_SOCKET_PATH=%s/wolf.sock", RuntimeDir)
	w("# WOLF_RENDER_NODE, found at every start by wolf-preflight: render node")
	w("# numbers can change across boots.")
	w("EnvironmentFile=%s", EnvFile)
	w("Environment=WOLF_USE_ZERO_COPY=%s", boolEnv(s.Wolf.ZeroCopy))
	w("Environment=WOLF_STOP_CONTAINER_ON_EXIT=TRUE")
	if b := s.Stream.PortBase; b != 0 && b != 47989 {
		w("Environment=WOLF_HTTP_PORT=%d", b)
		w("Environment=WOLF_HTTPS_PORT=%d", b-5)
		w("Environment=WOLF_CONTROL_PORT=%d", b+10)
		w("Environment=WOLF_RTSP_SETUP_PORT=%d", b+21)
		w("Environment=WOLF_VIDEO_PING_PORT=%d", b+111)
		w("Environment=WOLF_AUDIO_PING_PORT=%d", b+211)
	}
	w("")
	w("[Service]")
	w("# The first start pulls the image; stopping lets Wolf end its sessions.")
	w("TimeoutStartSec=900")
	w("TimeoutStopSec=60")
	if s.NVIDIA && s.Modprobe {
		w("# The device nodes the [Container] section requires (nvidia0 and")
		w("# nvidiactl; modeset; nvidia-uvm and -uvm-tools), whatever loaded so far.")
		w("# A failure here shows up as podman's missing device, with its name.")
		w("ExecStartPre=-/usr/bin/nvidia-modprobe -c0")
		w("ExecStartPre=-/usr/bin/nvidia-modprobe -m")
		w("ExecStartPre=-/usr/bin/nvidia-modprobe -u -c0")
	}
	w("# Refuses while the Incus game container runs, checks the home, finds the")
	w("# render node, clears leftover session containers, and merges xivstream's")
	w("# app into Wolf's config.")
	w("ExecStartPre=%s wolf-preflight", s.bin())
	w("# Wolf removes a session's container only when the session ends normally.")
	w("ExecStopPost=-%s wolf-cleanup", s.bin())
	w("Restart=on-failure")
	w("RestartSec=5")
	if s.Wolf.Autostart {
		w("")
		w("[Install]")
		w("WantedBy=multi-user.target")
	}
	return []byte(b.String())
}

func boolEnv(v bool) string {
	if v {
		return "TRUE"
	}
	return "FALSE"
}

// DriverVolUnitFile rebuilds the NVIDIA driver volume before Wolf, when the
// host's driver has changed since it was built.
func DriverVolUnitFile(s Setup) []byte {
	return []byte(fmt.Sprintf(`# xivstream: Wolf's NVIDIA driver volume (generated by xivstream)
[Unit]
Description=xivstream: NVIDIA driver volume for Wolf (rebuilt when the host driver changes)
After=network-online.target podman.socket
Wants=network-online.target
Before=%s

[Service]
Type=oneshot
RemainAfterExit=yes
# A no-op when %s matches /sys/module/nvidia/version; a rebuild
# downloads NVIDIA's installer once per driver version.
ExecStart=%s nvidia-driver-vol
TimeoutStartSec=1800
Nice=19
IOSchedulingClass=idle
`, Unit, DriverVolume, s.bin()))
}

// FirewallUnitFile loads the nft table while Wolf runs (PartOf: it goes when
// Wolf stops, so the legacy address's DNAT never outlives Wolf).
func FirewallUnitFile(s Setup) []byte {
	return []byte(fmt.Sprintf(`# xivstream: Wolf's network policy (generated by xivstream)
[Unit]
Description=xivstream: Wolf's firewall (tailnet-only Wolf ports, the session's network policy)
After=firewalld.service tailscaled.service
Before=%[1]s
PartOf=%[1]s

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f %[2]s
ExecStop=-/usr/sbin/nft delete table inet %[3]s
`, Unit, FirewallFile, Table))
}

// ForwardSocket listens on the bridge's gateway for one forward. FreeBind:
// the gateway address exists only while the Podman network is up.
func ForwardSocket(s Setup, f config.WolfForward) []byte {
	return []byte(fmt.Sprintf(`# xivstream: the Wolf session's %[1]s forward (generated by xivstream)
[Unit]
Description=xivstream: forward %[1]s for the Wolf session (%[2]s:%[3]d to %[4]s)

[Socket]
ListenStream=%[2]s:%[3]d
FreeBind=yes

[Install]
WantedBy=sockets.target
`, f.Name, s.Wolf.Gateway(), f.GatewayPort(), f.Target))
}

// ForwardService relays the socket's connections to the target.
func ForwardService(s Setup, f config.WolfForward) []byte {
	return []byte(fmt.Sprintf(`# xivstream: the Wolf session's %[1]s forward (generated by xivstream)
[Unit]
Description=xivstream: relay %[1]s to %[2]s for the Wolf session
Requires=%[3]s.socket
After=%[3]s.socket

[Service]
ExecStart=/usr/lib/systemd/systemd-socket-proxyd %[2]s
DynamicUser=yes
PrivateTmp=yes
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
`, f.Name, f.Target, ForwardUnit(f)))
}

// MountUnit mounts the home's subvolume by filesystem, not through Incus's
// pool mount (which only incusd makes, on demand).
func MountUnit(s Setup) []byte {
	return []byte(fmt.Sprintf(`# xivstream: the game's home for the Wolf session (generated by xivstream)
[Unit]
Description=xivstream: the game's home (btrfs subvolume %[1]s)

[Mount]
What=%[2]s
Where=%[3]s
Type=btrfs
Options=subvol=%[1]s

[Install]
WantedBy=multi-user.target
`, s.Wolf.HomeSubvolume, s.HomeDevice, s.Wolf.Home))
}

// FallbackUnitFile starts the Incus game container with Sunshine, from the
// config kept from before the switch to Wolf, and stops Wolf first. With
// wolf.autostart off (Wolf staged, not yet switched to) it is what starts at
// boot instead of Wolf.
func FallbackUnitFile(s Setup) []byte {
	install := ""
	if !s.Wolf.Autostart {
		install = "\n[Install]\nWantedBy=multi-user.target\n"
	}
	return []byte(fmt.Sprintf(`# xivstream: the Sunshine fallback (generated by xivstream)
#   systemctl start %[1]s   stops Wolf and starts the Incus game container
#   systemctl start %[2]s              switches back
# Log out of the game first either way: stopping a session gives the game
# seconds, not a clean exit.
[Unit]
Description=xivstream: Sunshine in the %[3]s Incus container (fallback for Wolf)
Conflicts=%[2]s
After=%[2]s %[4]s incus.service tailscaled.service network-online.target
# cpu-policy (busy/idle limits.cpu for the container) runs while this does.
Wants=incus.service network-online.target xivstream-cpu-policy.service

[Service]
Type=oneshot
RemainAfterExit=yes
Environment=XIVSTREAM_CONFIG=%[5]s
# Wolf's session containers can outlive Wolf; never run two games on one home.
ExecStartPre=%[6]s wolf-cleanup
ExecStart=%[6]s start-container
ExecStop=%[6]s stop-container
ExecStopPost=-/usr/bin/systemctl stop --no-block xivstream-cpu-policy.service
TimeoutStartSec=600
TimeoutStopSec=150
%[7]s`, FallbackUnit, Unit, s.GameContainer, FirewallUnit, FallbackConfig, s.bin(), install))
}
